// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Form is the predicate function for form builders.
type Form func(*sql.Selector)

// Todo is the predicate function for todo builders.
type Todo func(*sql.Selector)
