// Code generated by ent, DO NOT EDIT.

package todo

const (
	// Label holds the string label denoting the todo type in the database.
	Label = "todo"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTask holds the string denoting the task field in the database.
	FieldTask = "task"
	// EdgeForm holds the string denoting the form edge name in mutations.
	EdgeForm = "form"
	// Table holds the table name of the todo in the database.
	Table = "todo"
	// FormTable is the table that holds the form relation/edge.
	FormTable = "form"
	// FormInverseTable is the table name for the Form entity.
	// It exists in this package in order to avoid circular dependency with the "form" package.
	FormInverseTable = "form"
	// FormColumn is the table column denoting the form relation/edge.
	FormColumn = "todo_id"
)

// Columns holds all SQL columns for todo fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTask,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
