// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"hex-base/internal/core/adapters/repo/sql_type/sql/ent/lib/ent/form"
	"hex-base/internal/core/adapters/repo/sql_type/sql/ent/lib/ent/predicate"
	"hex-base/internal/core/adapters/repo/sql_type/sql/ent/lib/ent/todo"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FormUpdate is the builder for updating Form entities.
type FormUpdate struct {
	config
	hooks    []Hook
	mutation *FormMutation
}

// Where appends a list predicates to the FormUpdate builder.
func (fu *FormUpdate) Where(ps ...predicate.Form) *FormUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetCategory sets the "category" field.
func (fu *FormUpdate) SetCategory(s string) *FormUpdate {
	fu.mutation.SetCategory(s)
	return fu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (fu *FormUpdate) SetNillableCategory(s *string) *FormUpdate {
	if s != nil {
		fu.SetCategory(*s)
	}
	return fu
}

// ClearCategory clears the value of the "category" field.
func (fu *FormUpdate) ClearCategory() *FormUpdate {
	fu.mutation.ClearCategory()
	return fu
}

// SetTitle sets the "title" field.
func (fu *FormUpdate) SetTitle(s string) *FormUpdate {
	fu.mutation.SetTitle(s)
	return fu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (fu *FormUpdate) SetNillableTitle(s *string) *FormUpdate {
	if s != nil {
		fu.SetTitle(*s)
	}
	return fu
}

// ClearTitle clears the value of the "title" field.
func (fu *FormUpdate) ClearTitle() *FormUpdate {
	fu.mutation.ClearTitle()
	return fu
}

// SetStatus sets the "status" field.
func (fu *FormUpdate) SetStatus(s string) *FormUpdate {
	fu.mutation.SetStatus(s)
	return fu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fu *FormUpdate) SetNillableStatus(s *string) *FormUpdate {
	if s != nil {
		fu.SetStatus(*s)
	}
	return fu
}

// ClearStatus clears the value of the "status" field.
func (fu *FormUpdate) ClearStatus() *FormUpdate {
	fu.mutation.ClearStatus()
	return fu
}

// SetIsDeleted sets the "is_deleted" field.
func (fu *FormUpdate) SetIsDeleted(b bool) *FormUpdate {
	fu.mutation.SetIsDeleted(b)
	return fu
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (fu *FormUpdate) SetNillableIsDeleted(b *bool) *FormUpdate {
	if b != nil {
		fu.SetIsDeleted(*b)
	}
	return fu
}

// SetTodoID sets the "todo_id" field.
func (fu *FormUpdate) SetTodoID(i int32) *FormUpdate {
	fu.mutation.SetTodoID(i)
	return fu
}

// SetNillableTodoID sets the "todo_id" field if the given value is not nil.
func (fu *FormUpdate) SetNillableTodoID(i *int32) *FormUpdate {
	if i != nil {
		fu.SetTodoID(*i)
	}
	return fu
}

// ClearTodoID clears the value of the "todo_id" field.
func (fu *FormUpdate) ClearTodoID() *FormUpdate {
	fu.mutation.ClearTodoID()
	return fu
}

// SetTodo sets the "todo" edge to the Todo entity.
func (fu *FormUpdate) SetTodo(t *Todo) *FormUpdate {
	return fu.SetTodoID(t.ID)
}

// Mutation returns the FormMutation object of the builder.
func (fu *FormUpdate) Mutation() *FormMutation {
	return fu.mutation
}

// ClearTodo clears the "todo" edge to the Todo entity.
func (fu *FormUpdate) ClearTodo() *FormUpdate {
	fu.mutation.ClearTodo()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FormUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, FormMutation](ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FormUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FormUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FormUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FormUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   form.Table,
			Columns: form.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: form.FieldID,
			},
		},
	}
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Category(); ok {
		_spec.SetField(form.FieldCategory, field.TypeString, value)
	}
	if fu.mutation.CategoryCleared() {
		_spec.ClearField(form.FieldCategory, field.TypeString)
	}
	if value, ok := fu.mutation.Title(); ok {
		_spec.SetField(form.FieldTitle, field.TypeString, value)
	}
	if fu.mutation.TitleCleared() {
		_spec.ClearField(form.FieldTitle, field.TypeString)
	}
	if value, ok := fu.mutation.Status(); ok {
		_spec.SetField(form.FieldStatus, field.TypeString, value)
	}
	if fu.mutation.StatusCleared() {
		_spec.ClearField(form.FieldStatus, field.TypeString)
	}
	if value, ok := fu.mutation.IsDeleted(); ok {
		_spec.SetField(form.FieldIsDeleted, field.TypeBool, value)
	}
	if fu.mutation.TodoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   form.TodoTable,
			Columns: []string{form.TodoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: todo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.TodoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   form.TodoTable,
			Columns: []string{form.TodoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: todo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{form.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FormUpdateOne is the builder for updating a single Form entity.
type FormUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FormMutation
}

// SetCategory sets the "category" field.
func (fuo *FormUpdateOne) SetCategory(s string) *FormUpdateOne {
	fuo.mutation.SetCategory(s)
	return fuo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (fuo *FormUpdateOne) SetNillableCategory(s *string) *FormUpdateOne {
	if s != nil {
		fuo.SetCategory(*s)
	}
	return fuo
}

// ClearCategory clears the value of the "category" field.
func (fuo *FormUpdateOne) ClearCategory() *FormUpdateOne {
	fuo.mutation.ClearCategory()
	return fuo
}

// SetTitle sets the "title" field.
func (fuo *FormUpdateOne) SetTitle(s string) *FormUpdateOne {
	fuo.mutation.SetTitle(s)
	return fuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (fuo *FormUpdateOne) SetNillableTitle(s *string) *FormUpdateOne {
	if s != nil {
		fuo.SetTitle(*s)
	}
	return fuo
}

// ClearTitle clears the value of the "title" field.
func (fuo *FormUpdateOne) ClearTitle() *FormUpdateOne {
	fuo.mutation.ClearTitle()
	return fuo
}

// SetStatus sets the "status" field.
func (fuo *FormUpdateOne) SetStatus(s string) *FormUpdateOne {
	fuo.mutation.SetStatus(s)
	return fuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fuo *FormUpdateOne) SetNillableStatus(s *string) *FormUpdateOne {
	if s != nil {
		fuo.SetStatus(*s)
	}
	return fuo
}

// ClearStatus clears the value of the "status" field.
func (fuo *FormUpdateOne) ClearStatus() *FormUpdateOne {
	fuo.mutation.ClearStatus()
	return fuo
}

// SetIsDeleted sets the "is_deleted" field.
func (fuo *FormUpdateOne) SetIsDeleted(b bool) *FormUpdateOne {
	fuo.mutation.SetIsDeleted(b)
	return fuo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (fuo *FormUpdateOne) SetNillableIsDeleted(b *bool) *FormUpdateOne {
	if b != nil {
		fuo.SetIsDeleted(*b)
	}
	return fuo
}

// SetTodoID sets the "todo_id" field.
func (fuo *FormUpdateOne) SetTodoID(i int32) *FormUpdateOne {
	fuo.mutation.SetTodoID(i)
	return fuo
}

// SetNillableTodoID sets the "todo_id" field if the given value is not nil.
func (fuo *FormUpdateOne) SetNillableTodoID(i *int32) *FormUpdateOne {
	if i != nil {
		fuo.SetTodoID(*i)
	}
	return fuo
}

// ClearTodoID clears the value of the "todo_id" field.
func (fuo *FormUpdateOne) ClearTodoID() *FormUpdateOne {
	fuo.mutation.ClearTodoID()
	return fuo
}

// SetTodo sets the "todo" edge to the Todo entity.
func (fuo *FormUpdateOne) SetTodo(t *Todo) *FormUpdateOne {
	return fuo.SetTodoID(t.ID)
}

// Mutation returns the FormMutation object of the builder.
func (fuo *FormUpdateOne) Mutation() *FormMutation {
	return fuo.mutation
}

// ClearTodo clears the "todo" edge to the Todo entity.
func (fuo *FormUpdateOne) ClearTodo() *FormUpdateOne {
	fuo.mutation.ClearTodo()
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FormUpdateOne) Select(field string, fields ...string) *FormUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Form entity.
func (fuo *FormUpdateOne) Save(ctx context.Context) (*Form, error) {
	return withHooks[*Form, FormMutation](ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FormUpdateOne) SaveX(ctx context.Context) *Form {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FormUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FormUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FormUpdateOne) sqlSave(ctx context.Context) (_node *Form, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   form.Table,
			Columns: form.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: form.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Form.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, form.FieldID)
		for _, f := range fields {
			if !form.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != form.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Category(); ok {
		_spec.SetField(form.FieldCategory, field.TypeString, value)
	}
	if fuo.mutation.CategoryCleared() {
		_spec.ClearField(form.FieldCategory, field.TypeString)
	}
	if value, ok := fuo.mutation.Title(); ok {
		_spec.SetField(form.FieldTitle, field.TypeString, value)
	}
	if fuo.mutation.TitleCleared() {
		_spec.ClearField(form.FieldTitle, field.TypeString)
	}
	if value, ok := fuo.mutation.Status(); ok {
		_spec.SetField(form.FieldStatus, field.TypeString, value)
	}
	if fuo.mutation.StatusCleared() {
		_spec.ClearField(form.FieldStatus, field.TypeString)
	}
	if value, ok := fuo.mutation.IsDeleted(); ok {
		_spec.SetField(form.FieldIsDeleted, field.TypeBool, value)
	}
	if fuo.mutation.TodoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   form.TodoTable,
			Columns: []string{form.TodoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: todo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.TodoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   form.TodoTable,
			Columns: []string{form.TodoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt32,
					Column: todo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Form{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{form.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
