// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FormColumns holds the columns for the "form" table.
	FormColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "category", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(50)"}},
		{Name: "title", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(50)"}},
		{Name: "status", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(50)"}},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "todo_id", Type: field.TypeInt32, Nullable: true, SchemaType: map[string]string{"postgres": "integer"}},
	}
	// FormTable holds the schema information for the "form" table.
	FormTable = &schema.Table{
		Name:       "form",
		Columns:    FormColumns,
		PrimaryKey: []*schema.Column{FormColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "form_todo_form",
				Columns:    []*schema.Column{FormColumns[5]},
				RefColumns: []*schema.Column{TodoColumns[0]},
				OnDelete:   schema.Restrict,
			},
		},
	}
	// TodoColumns holds the columns for the "todo" table.
	TodoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt32, Increment: true, SchemaType: map[string]string{"postgres": "integer"}},
		{Name: "name", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(50)"}},
		{Name: "task", Type: field.TypeString, Nullable: true, SchemaType: map[string]string{"postgres": "varchar(200)"}},
	}
	// TodoTable holds the schema information for the "todo" table.
	TodoTable = &schema.Table{
		Name:       "todo",
		Columns:    TodoColumns,
		PrimaryKey: []*schema.Column{TodoColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FormTable,
		TodoTable,
	}
)

func init() {
	FormTable.ForeignKeys[0].RefTable = TodoTable
	FormTable.Annotation = &entsql.Annotation{
		Table: "form",
	}
	TodoTable.Annotation = &entsql.Annotation{
		Table: "todo",
	}
}
